const fs=require('fs');const P="C:\\Projects\\TinyDetect"+'/fresh';const log=m=>fs.appendFileSync(P+'/fetch.log',m+'\n');const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const UA={'User-Agent':'TinyDetect-eval/0.1 (ritabratamaiti@gmail.com)'};
(async()=>{try{
 const human=[];
 // 1) HN comments from 2012-2014 (pre-LLM, informal human writing)
 for(const q of ['programming','startup','bicycle','cooking','travel','music','school','health','history','physics']){const j=await (await fetch('https://hn.algolia.com/api/v1/search?tags=comment&query='+q+'&numericFilters=created_at_i<1388534400,created_at_i>1325376000&hitsPerPage=20')).json();for(const h of j.hits){const t=(h.comment_text||'').replace(/<p>/g,'\n\n').replace(/<[^>]+>/g,'').replace(/&#x27;/g,"'").replace(/&quot;/g,'"').replace(/&gt;/g,'>').replace(/&lt;/g,'<').replace(/&amp;/g,'&').replace(/&#x2F;/g,'/').trim();if(t.length>500&&t.length<2500&&!/http/.test(t)){human.push({src:'hn_2012',t});break;}}}
 // 2) Project Gutenberg passages (pre-1930 prose)
 for(const id of [1342,98,2701,84,1661,174,345,76]){try{const r=await fetch('https://www.gutenberg.org/cache/epub/'+id+'/pg'+id+'.txt',{headers:UA});const t=await r.text();const body=t.split(/\*\*\* ?START OF/)[1]||t;const paras=body.split(/\r?\n\s*\r?\n/).map(p=>p.replace(/\s+/g,' ').trim()).filter(p=>p.length>500&&p.length<1800&&!/[A-Z]{6,}/.test(p));human.push({src:'gutenberg_'+id,t:paras[Math.floor(paras.length*0.4)]});}catch(e){log('gut '+id+' '+e.message)}}
 // 3) Wikipedia article text as of 2019 (pre-LLM revisions)
 for(const title of ['Bicycle','Bread','Monsoon','Tea','Jazz','Lighthouse']){try{const u='https://en.wikipedia.org/w/api.php?action=query&prop=revisions&titles='+title+'&rvlimit=1&rvstart=2019-06-01T00:00:00Z&rvdir=older&rvprop=content&rvslots=main&format=json&formatversion=2';const j=await (await fetch(u,{headers:UA})).json();let w=j.query.pages[0].revisions[0].slots.main.content;w=w.replace(/\{\{[^{}]*\}\}/g,'').replace(/\{\{[^{}]*\}\}/g,'').replace(/<ref[^>]*\/>/g,'').replace(/<ref[\s\S]*?<\/ref>/g,'').replace(/\[\[(?:[^|\]]*\|)?([^\]]+)\]\]/g,'$1').replace(/'''?/g,'').replace(/<[^>]+>/g,'');const paras=w.split(/\n\n+/).map(p=>p.trim()).filter(p=>p.length>500&&!/^[=*|{!\[]/.test(p));if(paras[0])human.push({src:'wikipedia2019_'+title,t:paras[0].slice(0,1800)});}catch(e){log('wiki '+title+' '+e.message)}}
 fs.writeFileSync(P+'/human_text.json',JSON.stringify(human,null,1));log('human text '+human.length);
 // images: real photos = Wikimedia Commons quality images (uploaded 2010-2018); AI = Midjourney dataset
 const real=[];const cm=await (await fetch('https://commons.wikimedia.org/w/api.php?action=query&generator=categorymembers&gcmtitle=Category:Quality_images_of_landscapes&gcmtype=file&gcmlimit=40&prop=imageinfo&iiprop=url|timestamp&iiurlwidth=640&format=json&formatversion=2',{headers:UA})).json();
 for(const p of (cm.query&&cm.query.pages)||[]){const ii=p.imageinfo&&p.imageinfo[0];if(!ii||!ii.thumburl||ii.timestamp>'2019')continue;real.push(ii.thumburl);}
 const cm2=await (await fetch('https://commons.wikimedia.org/w/api.php?action=query&generator=categorymembers&gcmtitle=Category:Quality_images_of_people&gcmtype=file&gcmlimit=40&prop=imageinfo&iiprop=url|timestamp&iiurlwidth=640&format=json&formatversion=2',{headers:UA})).json();
 for(const p of (cm2.query&&cm2.query.pages)||[]){const ii=p.imageinfo&&p.imageinfo[0];if(!ii||!ii.thumburl||ii.timestamp>'2019')continue;real.push(ii.thumburl);}
 let n=0;for(const u of real.slice(0,30)){try{const r=await fetch(u,{headers:UA});if(!r.ok)continue;fs.writeFileSync(P+'/img/real_'+(n++)+'.jpg',Buffer.from(await r.arrayBuffer()));await sleep(150);}catch(e){}}log('real imgs '+n);
 let a=0;for(const off of [0,300,700,1100]){const r=await (await fetch('https://datasets-server.huggingface.co/rows?dataset=ideepankarsharma2003/AIGeneratedImages_Midjourney&config=default&split=train&offset='+off+'&length=8')).json();for(const x of (r.rows||[])){const im=x.row.image||Object.values(x.row).find(v=>v&&v.src);if(!im||!im.src)continue;try{const b=await fetch(im.src);if(b.ok){fs.writeFileSync(P+'/img/ai_mj_'+(a++)+'.jpg',Buffer.from(await b.arrayBuffer()));}}catch(e){}}await sleep(500);}
 log('ai imgs '+a);log('DONE');}catch(e){log('ERR '+e.stack)}})();