const fs=require('fs');const P="C:\\Projects\\TinyDetect"+'/fresh2';const log=m=>fs.appendFileSync(P+'/fetch.log',m+'\n');const sleep=ms=>new Promise(r=>setTimeout(r,ms));const UA={'User-Agent':'TinyDetect-eval/0.1 (ritabratamaiti@gmail.com)'};
const clean=s=>s.replace(/<p>/g,'\n\n').replace(/<[^>]+>/g,'').replace(/&#x27;/g,"'").replace(/&quot;/g,'"').replace(/&gt;/g,'>').replace(/&lt;/g,'<').replace(/&amp;/g,'&').replace(/&#x2F;/g,'/').trim();
(async()=>{try{const human=[];
 for(const q of ['database','gardening','parenting','linux','economics','camera','running','teacher','movie','airline']){const j=await (await fetch('https://hn.algolia.com/api/v1/search?tags=comment&query='+q+'&numericFilters=created_at_i<1420070400,created_at_i>1388534400&hitsPerPage=25')).json();for(const h of j.hits){const t=clean(h.comment_text||'');if(t.length>500&&t.length<2500&&!/http/.test(t)){human.push({src:'hn_2014',t});break;}}}
 for(const id of [84,98,1661,76,1260,1400,158,219]){try{const t=await (await fetch('https://www.gutenberg.org/cache/epub/'+id+'/pg'+id+'.txt',{headers:UA})).text();const body=t.split(/\*\*\* ?START OF/)[1]||t;const ps=body.split(/\r?\n\s*\r?\n/).map(p=>p.replace(/\s+/g,' ').trim()).filter(p=>p.length>500&&p.length<1800&&!/[A-Z]{6,}/.test(p));human.push({src:'gutenberg2_'+id,t:ps[Math.floor(ps.length*0.65)]});}catch(e){log('gut '+id)}}
 for(const title of ['Volcano','Chess','Coffee','Bridge','Penguin','Opera']){try{const u='https://en.wikipedia.org/w/api.php?action=query&prop=revisions&titles='+title+'&rvlimit=1&rvstart=2019-06-01T00:00:00Z&rvdir=older&rvprop=content&rvslots=main&format=json&formatversion=2';const j=await (await fetch(u,{headers:UA})).json();let w=j.query.pages[0].revisions[0].slots.main.content;for(let k=0;k<3;k++)w=w.replace(/\{\{[^{}]*\}\}/g,'');w=w.replace(/<ref[^>]*\/>/g,'').replace(/<ref[\s\S]*?<\/ref>/g,'').replace(/\[\[(?:File|Image):[^\]]*\]\]/g,'').replace(/\[\[(?:[^|\]]*\|)?([^\]]+)\]\]/g,'$1').replace(/'''?/g,'').replace(/<[^>]+>/g,'');const ps=w.split(/\n\n+/).map(p=>p.trim()).filter(p=>p.length>500&&!/^[=*|{!\[]/.test(p)&&!/thumb\|/.test(p));if(ps[1])human.push({src:'wikipedia2019b_'+title,t:ps[1].slice(0,1800)});}catch(e){log('wiki '+title)}}
 fs.writeFileSync(P+'/human_text.json',JSON.stringify(human,null,1));log('human text '+human.length);
 let n=0;for(const cat of ['Quality_images_of_animals','Quality_images_of_buildings','Quality_images_of_food']){const cm=await (await fetch('https://commons.wikimedia.org/w/api.php?action=query&generator=categorymembers&gcmtitle=Category:'+cat+'&gcmtype=file&gcmlimit=30&prop=imageinfo&iiprop=url|timestamp&iiurlwidth=800&format=json&formatversion=2',{headers:UA})).json();let k=0;for(const p of (cm.query&&cm.query.pages)||[]){const ii=p.imageinfo&&p.imageinfo[0];if(!ii||!ii.thumburl||ii.timestamp>'2019'||k>=10)continue;try{const r=await fetch(ii.thumburl,{headers:UA});if(r.ok){fs.writeFileSync(P+'/img/real_'+(n++)+'.jpg',Buffer.from(await r.arrayBuffer()));k++;}}catch(e){}await sleep(150);}}log('real '+n);
 let a=0;async function grab(ds,tag,offs,per){try{const sp=await (await fetch('https://datasets-server.huggingface.co/splits?dataset='+ds)).json();const s=sp.splits[0];for(const o of offs){const r=await (await fetch('https://datasets-server.huggingface.co/rows?dataset='+ds+'&config='+s.config+'&split='+s.split+'&offset='+o+'&length='+per)).json();for(const x of (r.rows||[])){const im=Object.values(x.row).find(v=>v&&typeof v==='object'&&v.src);if(!im)continue;try{const b=await fetch(im.src);if(b.ok){fs.writeFileSync(P+'/img/ai_'+tag+'_'+(a++)+'.jpg',Buffer.from(await b.arrayBuffer()));}}catch(e){}}await sleep(600);}}catch(e){log('ERR '+ds+' '+e.message)}log(tag+' total ai '+a);}
 await grab('ideepankarsharma2003/AIGeneratedImages_Midjourney','mj',[1500,1900,2300],5);await grab('strangerzonehf/Flux-Generated-Super-Portrait','fluxportrait',[0,20,40],4);await grab('ehristoforu/dalle-3-images','dalle3b',[0,100,200],4);
 log('DONE');}catch(e){log('ERR '+e.stack)}})();